"""add examples and synonyms to dictionary

Revision ID: c8e2dca51e1c
Revises: 
Create Date: 2026-04-05 20:57:33.535631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e2dca51e1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examples', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('synonyms', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary_table', schema=None) as batch_op:
        batch_op.drop_column('synonyms')
        batch_op.drop_column('examples')

    # ### end Alembic commands ###
