// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeJPlmKl9FflKLGAKTeTedqzwnI2Bk8M',
    appId: '1:540329046513:web:15fdf688c9bc85c6571450',
    messagingSenderId: '540329046513',
    projectId: 'kebena-heritage',
    authDomain: 'kebena-heritage.firebaseapp.com',
    storageBucket: 'kebena-heritage.firebasestorage.app',
    measurementId: 'G-J90S2Q4H3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRn0cwQGYVA6PJ6NBk6C5lcTafnrtLvaE',
    appId: '1:540329046513:android:398866b83be4cade571450',
    messagingSenderId: '540329046513',
    projectId: 'kebena-heritage',
    storageBucket: 'kebena-heritage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOQGXNgVS6vF8x7SOpsXWcs0KbVzOhb1g',
    appId: '1:540329046513:ios:63cb44e6fc2d50de571450',
    messagingSenderId: '540329046513',
    projectId: 'kebena-heritage',
    storageBucket: 'kebena-heritage.firebasestorage.app',
    iosBundleId: 'com.kebena.heritage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOQGXNgVS6vF8x7SOpsXWcs0KbVzOhb1g',
    appId: '1:540329046513:ios:63cb44e6fc2d50de571450',
    messagingSenderId: '540329046513',
    projectId: 'kebena-heritage',
    storageBucket: 'kebena-heritage.firebasestorage.app',
    iosBundleId: 'com.kebena.heritage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOeJPlmKl9FflKLGAKTeTedqzwnI2Bk8M',
    appId: '1:540329046513:web:32afc4378c43f6bb571450',
    messagingSenderId: '540329046513',
    projectId: 'kebena-heritage',
    authDomain: 'kebena-heritage.firebaseapp.com',
    storageBucket: 'kebena-heritage.firebasestorage.app',
    measurementId: 'G-HEWX9RQJM5',
  );

}